# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = true
biomeParticlesRadius = 20
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 5
fireflyBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp"
]
fireflyDensity = 6
pollenBiomes = [
    "minecraft:flower_forest",
    "minecraft:sunflower_plains"
]
pollenDensity = 25
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 5