# Don't change this! Version used to track needed updates.
version = 0
enderPearlTrail = true
snowballTrailDensity = 0.5
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartSparksDisplayType = "DEFAULT"
minecartSparksDensity = 0.3
slimeTrails = true
magmaCubeTrails = true
replaceSlimeSquishParticles = true
replaceOozingEffectParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
xpBottleParticlesDisplayType = "DEFAULT"
xpBottleParticlesDensity = 7
eggSmashSoundVolume = 0.3
freezingSnowFlakes = true

[attacked]
chickenFeathers = true
parrotFeathers = true
snowGolemSnowflakes = true

[sleeping]
playerSnoreChance = 0.0
playerSnoreSoundVolume = 1.0
playersHaveSleepingZs = true
villagerSnoreChance = 0.0
villagerSnoreSoundVolume = 1.0
villagersHaveSleepingZs = true
foxesHaveSleepingZs = true
batsHaveSleepingZs = true
catsHaveSleepingZs = true
otherMobsHaveSleepingZs = true
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubblesDisplayType = "DEFAULT"
drowningBubblesDensity = 10
drowningBubbleAlpha = 1.0
potionRingsDisplayType = "DEFAULT"
potionRingsParticleType = "BOTH"
NPCsHavePotionRings = true

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.5
waitTime = 60
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 0.0
heartBeatingThreshold = 6
heartbeatVolume = 0.0

[dustClouds]
scale = 1.5
alpha = 0.7
preventWhenRaining = false
flyIntoWall = true
lessViewBlocking = true
playerFell = true
mobFell = true
landMaceAttack = true
playerRunning = true
mobRunning = true
playerRunningRequiresSpeed = false

[burning]
smoke = "DEFAULT"
flames = true
sparks = true
sounds = true
extinguishSteam = true

[itemRarity]
particlesDisplayType = "ON"
particleColorType = "NAME_COLOR"
mixedColorName = true
useItemBorder = true
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 0.5

[explosives]
tntUpdateSmoke = true
tntFlamesDensity = 1
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true