// priority: 0

// Visit the wiki for more info - https://kubejs.com/

console.info('Hello, World! (Loaded client scripts)')

JEIEvents.hideItems(event => {
	// Hide items in JEI here
	// event.hide('minecraft:cobblestone')
	
	event.hide('industrialforegoing:plastic')
	event.hide('industrialforegoing:dryrubber')
	event.hide('industrialforegoing:tinydryrubber')
	event.hide('industrialforegoing:latex_processing_unit')
	
	event.hide('mffs:steel_compound') 
	event.hide('mffs:steel_ingot') 
	event.hide('railcraft:lead_raw')
	event.hide('railcraft:iron_plate')
	event.hide('railcraft:lead_ingot') 
	event.hide('railcraft:lead_plate') 
	event.hide('railcraft:lead_ore') 
	event.hide('railcraft:deepslate_lead_ore') 
	event.hide('railcraft:lead_block') 
	event.hide('railcraft:lead_nugget') 
	event.hide('railcraft:steel_ingot') 
	event.hide('railcraft:steel_plate') 
	event.hide('railcraft:steel_block') 
	event.hide('railcraft:steel_nugget') 
	event.hide('railcraft:nickel_ore') 
	event.hide('railcraft:nickel_ingot') 
	event.hide('railcraft:deepslate_nickel_ore') 
	event.hide('railcraft:nickel_raw') 
	event.hide('railcraft:nickel_block') 
	event.hide('railcraft:nickel_nugget') 
	event.hide('railcraft:nickel_plate') 
	event.hide('railcraft:silver_plate') 
	event.hide('railcraft:silver_ingot') 
	event.hide('railcraft:silver_ore') 
	event.hide('railcraft:deepslate_silver_ore') 
	event.hide('railcraft:silver_raw') 
	event.hide('railcraft:silver_block') 
	event.hide('railcraft:silver_nugget') 
	event.hide('ad_astra:steel_ingot') 
	event.hide('ad_astra:steel_plate') 
	event.hide('ad_astra:iron_plate')
	event.hide('railcraft:copper_plate')
	event.hide('railcraft:gold_plate')
	
	event.hide('railcraft:steel_shovel')
	event.hide('railcraft:steel_pickaxe')
	event.hide('railcraft:steel_axe')
	event.hide('railcraft:steel_hoe')
	event.hide('railcraft:steel_sword')
	event.hide('railcraft:steel_helmet')
	event.hide('railcraft:steel_chestplate')
	event.hide('railcraft:steel_leggings')
	event.hide('railcraft:steel_boots')
	
	event.hide('industrialforegoing:conveyor')
	event.hide('industrialforegoing:conveyor_extraction_upgrade')
	event.hide('industrialforegoing:conveyor_detection_upgrade')
	event.hide('industrialforegoing:conveyor_insertion_upgrade')
	event.hide('industrialforegoing:conveyor_bouncing_upgrade')
	event.hide('railcraft:coke_oven_bricks')
	event.hide('railcraft:blast_furnace_bricks')
	event.hide('ad_astra:coal_generator')
	event.hide('ad_astra:fuel_refinery')
	event.hide('ad_astra:solar_panel')
	event.hide('industrialforegoing:mob_imprisonment_tool')
	event.hide('industrialforegoing:conveyor_dropping_upgrade')
	event.hide('industrialforegoing:conveyor_blinking_upgrade')
	event.hide('industrialforegoing:conveyor_splitting_upgrade')
	
	event.hide('industrialforegoing:mycelial_reactor')
	event.hide('industrialforegoing:mycelial_furnace')
	event.hide('industrialforegoing:mycelial_slimey')
	event.hide('industrialforegoing:mycelial_culinary')
	event.hide('industrialforegoing:mycelial_potion')
	event.hide('industrialforegoing:mycelial_ender')
	event.hide('industrialforegoing:mycelial_explosive')
	event.hide('industrialforegoing:mycelial_frosty')
	event.hide('industrialforegoing:mycelial_halitosis')
	event.hide('industrialforegoing:mycelial_magma')
	event.hide('industrialforegoing:mycelial_pink')
	event.hide('industrialforegoing:mycelial_netherstar')
	event.hide('industrialforegoing:mycelial_death')
	event.hide('industrialforegoing:mycelial_rocket')
	event.hide('industrialforegoing:mycelial_crimed')
	event.hide('industrialforegoing:mycelial_meatallurgic')
	event.hide('industrialforegoing:pitiful_generator')
	event.hide('industrialforegoing:mob_imprisonment_tool')
	event.hide('ad_astra:coal_generator')
	event.hide('ad_astra:fuel_refinery')
	event.hide('ad_astra:solar_panel')
	
	event.hide('advgenerators:iron_frame')
	event.hide('advgenerators:iron_tubing')
	event.hide('advgenerators:iron_wiring')
	event.hide('advgenerators:controller')
	event.hide('advgenerators:pressure_valve')
	event.hide('advgenerators:advanced_pressure_valve')
	event.hide('advgenerators:turbine_blade')
	event.hide('advgenerators:turbine_rotor_tier2')
	event.hide('advgenerators:turbine_rotor_tier3')
	event.hide('advgenerators:turbine_rotor_tier4')
	event.hide('advgenerators:turbine_rotor_tier5')
	event.hide('advgenerators:power_io')
	
	event.hide('toms_storage:ts.trim')
	event.hide('toms_storage:ts.open_crate')
	event.hide('toms_storage:ts.inventory_cable')
	event.hide('toms_storage:ts.inventory_cable_framed')
	event.hide('toms_storage:ts.inventory_cable_connector')
	event.hide('toms_storage:ts.inventory_cable_connector_framed')
	event.hide('toms_storage:ts.inventory_cable_connector_filtered')
	event.hide('toms_storage:ts.inventory_proxy')
	event.hide('toms_storage:ts.inventory_hopper_basic')
	event.hide('toms_storage:ts.wireless_terminal')
	event.hide('toms_storage:ts.adv_wireless_terminal')
	event.hide('toms_storage:ts.item_filter')
	event.hide('toms_storage:ts.polymorphic_item_filter')
	event.hide('toms_storage:ts.tag_item_filter')
	event.hide('toms_storage:ts.trim')
	event.hide('toms_storage:ts.level_emitter')
	event.hide('toms_storage:ts.adv_wireless_terminal')
	event.hide('toms_storage:ts.paint_kit')	
	
	event.hide('functionalstorage:framed_controller_extension')
	event.hide('functionalstorage:fluid_1')
	event.hide('functionalstorage:fluid_2')
	event.hide('functionalstorage:fluid_4')
	event.hide('functionalstorage:compacting_drawer')
	event.hide('functionalstorage:compacting_framed_drawer')
	event.hide('functionalstorage:storage_controller')
	event.hide('functionalstorage:framed_storage_controller')
	event.hide('functionalstorage:controller_extension')
	event.hide('functionalstorage:linking_tool')
	event.hide('functionalstorage:simple_compacting_drawer')
	event.hide('functionalstorage:framed_simple_compacting_drawer')
	event.hide('functionalstorage:armory_cabinet')
	event.hide('functionalstorage:ender_drawer')	
	
	event.hide('sophisticatedbackpacks:compacting_upgrade')
	event.hide('sophisticatedbackpacks:advanced_compacting_upgrade')
	event.hide('sophisticatedbackpacks:inception_upgrade')
	event.hide('sophisticatedbackpacks:smelting_upgrade')
	event.hide('sophisticatedbackpacks:auto_smelting_upgrade')
	event.hide('sophisticatedbackpacks:smoking_upgrade')
	event.hide('sophisticatedbackpacks:auto_smoking_upgrade')
	event.hide('sophisticatedbackpacks:xp_pump_upgrade')
	event.hide('sophisticatedbackpacks:blasting_upgrade')
	event.hide('sophisticatedbackpacks:auto_blasting_upgrade')
	event.hide('sophisticatedbackpacks:stonecutter_upgrade')
	event.hide('sophisticatedbackpacks:tank_upgrade')
	event.hide('sophisticatedbackpacks:battery_upgrade')
	event.hide('sophisticatedbackpacks:pump_upgrade')
	event.hide('sophisticatedbackpacks:advanced_pump_upgrade')
})