#Whether backpacks can have their resupply mode enabled, which stocks a player's inventory using blocks from the backpack's inventory.
enable_backpack_resupply = true

[genetics]
	#When a player researches a mutation using the Escritoire, mutation chances for hives owned by that player are multiplied by this factor, with the increase in chance limited to the value set in "research_mutation_boost_multiplier".
	#Range: 1.0 ~ 1000.0
	research_mutation_boost_multiplier = 1.5
	#When a player researchs a mutation using the Escritoire, mutation chances for hives owned by that player are multiplied by a certain factor, with the increase in chance capped to this value.
	#Range: 0.0 ~ 100.0
	max_research_mutation_boost_percent = 5.0

[bees]
	#Whether bees and butterflies can pollinate Vanilla leaves. Might be undesirable for builds that rely on leaves.
	pollinate_vanilla_leaves = true
	#The base chance for a wild beehive to spawn naturally.
	#Range: 0.0 ~ 1000.0
	wild_hive_spawn_rate = 1.0
	#In real life, drone bees are haploid, which means they only carry one set of chromosomes. If this option is enabled, only a drone's active alleles will be used for inheritance, making drones effectively haploid. This CHANGES Forestry's bee breeding mechanics.
	use_haploid_drones = false

[farming]
	#
	#Range: 1 ~ 10
	multiblock_farm_size = 2
	#Whether Forestry multiblock farms have square shaped farmlands instead of the default diamond shape.
	square_multiblock_farms = false
	#Sets the size of the farmland that is used by all legacy (single block) farms.
	#Range: 1 ~ 10
	legacy_farms_planter_rings = 4
	#Whether legacy (single block) farms use a ring layout. The farmland size of the ring layout is always one block smaller.
	legacy_farms_use_rings = true
	#Sets the size of the inner ring of the ring layout.
	#Range: 1 ~ 10
	legacy_farms_ring_size = 4

[butterflies]
	#The maximum number of butterflies that can spawn in the same area or cluster.
	#Range: 1 ~ 2000
	butterfly_cluster_limit = 1
	#The width of the cluster area used when checking if the "butterfly_cluster_limit" has been reached.
	#Range: 0 ~ 2000
	butterfly_cluster_width = 128
	#The height of the cluster area used when checking if the "butterfly_cluster_limit" has been reached.
	#Range: 0 ~ 2000
	butterfly_cluster_height = 64
	#Whether butterflies can spawn from Forestry leaves.
	disable_butterfly_spawning = true

[trees]
	#Multiplies the chance of a Forestry tree spawning in the wild. Set to 0 to disable Forestry tree spawning.
	#Range: 0.0 ~ 1000000.0
	tree_spawn_chance_modifier = 0.0

