# Use Cloth Config mod for the descriptions.
---
cherryParticle: Modded
moddedCherryParticleFrequency: 32
food:
  specialEffectTooltip: true
  statusEffectTooltip: true
beehiveTooltipDisplayBees: true
