
[worldGens]
	#Range: 0.0 ~ 1.0
	emptyColoniesGenerationChance = 1.0

[buildings]
	customCraftingModules = ["{\"name\": \"sawmill_planks\", \"buildingId\": \"sawmill\", \"jobId\": \"sawmill\", \"forceVisible\": true}", "{\"name\": \"bricks\", \"buildingId\": \"stonesmeltery\", \"jobId\": \"stonesmeltery\", \"forceVisible\": true}"]

