
["Stellar View Client Config"]

	["Stellar View Client Config"."General Config"]

		["Stellar View Client Config"."General Config".client]
			#Gets rid of any rotation caused by the view center, making the space XYZ coordinates align with the XYZ directions in Minecraft
			disable_view_center_rotation = false
			#Removes Stars
			disable_stars = false
			#Makes Stars brighter
			bright_stars = true

	["Stellar View Client Config"."Overworld Config"]

		["Stellar View Client Config"."Overworld Config".client]
			#Controls how much the Overworld sky rotates when moving along the Z-axis
			#Range: 0 ~ 3000
			overworld_z_rotation_multiplier = 3000

			["Stellar View Client Config"."Overworld Config".client.overworld]
				#Replaces the Vanilla Overworld sky with Stellar View sky
				replace_vanilla = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Stars will always be visible, even during daytime
				stars_always_visible = false
				#Chance of a meteor shower happening each day
				#Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				#Range: 0 ~ 100
				shooting_star_chance = 10
				#Specifies Sol X offset
				#Range: -120 ~ 120
				sol_x_offset = 0
				#Specifies Sol Y offset
				#Range: -120 ~ 120
				sol_y_offset = 0
				#Specifies Sol Z offset
				#Range: -120 ~ 120
				sol_z_offset = 0
				#Specifies Sol X-axis rotation
				#Range: 0 ~ 360
				sol_x_rotation = 0
				#Specifies Sol Y-axis rotation
				#Range: 0 ~ 360
				sol_y_rotation = 0
				#Specifies Sol Z-axis rotation
				#Range: 0 ~ 360
				sol_z_rotation = 0

	["Stellar View Client Config"."Nether Config"]

		["Stellar View Client Config"."Nether Config".client]

			["Stellar View Client Config"."Nether Config".client.nether]
				#Replaces the Vanilla Nether sky with Stellar View sky
				replace_vanilla = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Stars will always be visible, even during daytime
				stars_always_visible = false
				#Chance of a meteor shower happening each day
				#Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				#Range: 0 ~ 100
				shooting_star_chance = 10

	["Stellar View Client Config"."End Config"]

		["Stellar View Client Config"."End Config".client]

			["Stellar View Client Config"."End Config".client.end]
				#Replaces the Vanilla End sky with Stellar View sky
				replace_vanilla = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Stars will always be visible, even during daytime
				stars_always_visible = true
				#Chance of a meteor shower happening each day
				#Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				#Range: 0 ~ 100
				shooting_star_chance = 10

